export const categoryActionTypes = {
  CATEGORY_REQUEST_INITIATED: "CATEGORY_REQUEST_INITIATED",
  CATEGORY_FIND_ALL_REQUEST: "CATEGORY_FIND_ALL_REQUEST",
  CATEGORY_FIND_ALL_REQUEST_SUCCEED: "CATEGORY_FIND_ALL_REQUEST_SUCCEED",
  CATEGORY_FIND_ALL_REQUEST_FAILED: "CATEGORY_FIND_ALL_REQUEST_FAILED",
  CATEGORY_FIND_BY_ID_REQUEST: "CATEGORY_FIND_ALL_REQUEST",
  CATEGORY_FIND_BY_ID_REQUEST_SUCCEED: "CATEGORY_FIND_ALL_REQUEST_SUCCEED",
  CATEGORY_FIND_BY_ID_REQUEST_FAILED: "CATEGORY_FIND_ALL_REQUEST_FAILED",
  CATEGORY_QUERY_REQUEST: "CATEGORY_QUERY_REQUEST",
  CATEGORY_QUERY_REQUEST_SUCCEED: "CATEGORY_QUERY_REQUEST_SUCCEED",
  CATEGORY_QUERY_REQUEST_FAILED: "CATEGORY_QUERY_REQUEST_FAILED"
};

export const productActionTypes = {
  PRODUCT_QUERY_REQUEST: "PRODUCT_QUERY_REQUEST",
  PRODUCT_FIND_ALL_REQUEST: "PRODUCT_FIND_ALL_REQUEST",
  PRODUCT_FIND_BY_ID_REQUEST: "PRODUCT_FIND_BY_ID_REQUEST",
  PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
  PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  PRODUCT_REQUEST_SUCCEED: "PRODUCT_REQUEST_SUCCEED",
  PRODUCT_REQUEST_FAILED: "PRODUCT_REQUEST_FAILED",
  PRODUCT_DELETE_SUCCEED: "PRODUCT_DELETE_SUCCEED"
};

export const productBrandActionTypes = {
  "PRODUCT-BRAND_FIND_ALL_REQUEST": "PRODUCT-BRAND_FIND_ALL_REQUEST",
  "PRODUCT-BRAND_FIND_BY_ID_REQUEST": "PRODUCT-BRAND_FIND_BY_ID_REQUEST",
  "PRODUCT-BRAND_QUERY_REQUEST": "PRODUCT-BRAND_QUERY_REQUEST",
  "PRODUCT-BRAND_REQUEST_SUCCEED": "PRODUCT-BRAND_REQUEST_SUCCEED",
  "PRODUCT-BRAND_REQUEST_FAILED": "PRODUCT-BRAND_REQUEST_FAILED",
  "PRODUCT-BRAND_DELETE_REQUEST": "PRODUCT-BRAND_DELETE_REQUEST",
  "PRODUCT-BRAND_DELETE_SUCCEED": "PRODUCT-BRAND_DELETE_SUCCEED",
  "PRODUCT-BRAND_RESET_DATA": "PRODUCT-BRAND_RESET_DATA"
};

export const productBrandUnitActionTypes = {
  "PRODUCT-BRAND-UNIT_FIND_ALL_REQUEST": "PRODUCT-BRAND-UNIT_FIND_ALL_REQUEST",
  "PRODUCT-BRAND-UNIT_FIND_BY_ID_REQUEST": "PRODUCT-BRAND-UNIT_FIND_BY_ID_REQUEST",
  "PRODUCT-BRAND-UNIT_QUERY_REQUEST": "PRODUCT-BRAND-UNIT_QUERY_REQUEST",
  "PRODUCT-BRAND-UNIT_REQUEST_SUCCEED": "PRODUCT-BRAND-UNIT_REQUEST_SUCCEED",
  "PRODUCT-BRAND-UNIT_REQUEST_FAILED": "PRODUCT-BRAND-UNIT_REQUEST_FAILED",
  "PRODUCT-BRAND-UNIT_DELETE_REQUEST": "PRODUCT-BRAND-UNIT_DELETE_REQUEST",
  "PRODUCT-BRAND-UNIT_DELETE_SUCCEED": "PRODUCT-BRAND-UNIT_DELETE_SUCCEED",
  "PRODUCT-BRAND-UNIT_RESET_DATA": "PRODUCT-BRAND-UNIT_RESET_DATA"
};

export const sessionActionTypes = {
  AUTHENTICATION_REQUEST_INITIATED: "AUTHENTICATION_REQUEST_INITIATED",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  UNAUTHENTICATED_SUCCESS: "UNAUTHENTICATED_SUCCESS",
  UNAUTHENTICATED_REQUEST_INITIATED: "UNAUTHENTICATED_REQUEST_INITIATED",
  AUTHENTICATION_REQUEST_FAILED: "AUTHENTICATION_REQUEST_FAILED"
};

export const sellerProductActionTypes = {
  "SELLER-PRODUCT_QUERY_REQUEST": "SELLER-PRODUCT_QUERY_REQUEST",
  "SELLER-PRODUCT_FIND_ALL_REQUEST": "SELLER-PRODUCT_FIND_ALL_REQUEST",
  "SELLER-PRODUCT_FIND_BY_ID_REQUEST": "SELLER-PRODUCT_FIND_BY_ID_REQUEST",
  "SELLER-PRODUCT_CREATE_REQUEST": "SELLER-PRODUCT_CREATE_REQUEST",
  "SELLER-PRODUCT_UPDATE_REQUEST": "SELLER-PRODUCT_UPDATE_REQUEST",
  "SELLER-PRODUCT_DELETE_REQUEST": "SELLER-PRODUCT_DELETE_REQUEST",
  "SELLER-PRODUCT_SUCCEED": "SELLER-PRODUCT_SUCCEED",
  "SELLER-PRODUCT_FAILED": "SELLER-PRODUCT_FAILED",
  "SELLER-PRODUCT_DELETE_SUCCEED": "SELLER-PRODUCT_DELETE_SUCCEED",
  "SELLER-PRODUCT_FIND_BY_BARCODE_REQUEST": "SELLER-PRODUCT_FIND_BY_BARCODE_REQUEST"
};
