export const sessionActionTypes = {
  AUTHENTICATION_REQUEST_INITIATED: "AUTHENTICATION_REQUEST_INITIATED",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  UNAUTHENTICATED_SUCCESS: "UNAUTHENTICATED_SUCCESS",
  UNAUTHENTICATED_REQUEST_INITIATED: "UNAUTHENTICATED_REQUEST_INITIATED",
  AUTHENTICATION_REQUEST_FAILED: "AUTHENTICATION_REQUEST_FAILED",
  AUTHENTICATION_OTP_REQUEST: "AUTHENTICATION_OTP_REQUEST",
  USER_REQUEST_INITIATED: "USER_REQUEST_INITIATED"
};

export const userActionTypes = {
  USER_REQUEST_INITIATED: "USER_REQUEST_INITIATED",
  USER_REQUEST_SUCCESS: "USER_REQUEST_SUCCESS",
  USER_REQUEST_FAILED: "USER_REQUEST_FAILED"
};

export const memberActionTypes = {
  MEMBER_CREATE_REQUEST_INITIATED: "MEMBER_CREATE_REQUEST_INITIATED",
  MEMBER_UPDATE_REQUEST_INITIATED: "MEMBER_UPDATE_REQUEST_INITIATED",
  MEMBER_DELETE_REQUEST_INITIATED: "MEMBER_DELETE_REQUEST_INITIATED",
  MEMBER_FIND_ALL_REQUEST_INITIATED: "MEMBER_FIND_ALL_REQUEST_INITIATED",
  MEMBER_FIND_BY_ID_REQUEST_INITIATED: "MEMBER_FIND_BY_ID_REQUEST_INITIATED",
  MEMBER_REQUEST_SUCCEED: "MEMBER_REQUEST_SUCCEED",
  MEMBER_REQUEST_FAILED: "MEMBER_REQUEST_FAILED",
  MEMBER_BOOK_APPOINTMENT_REQUEST_INITIATED: "MEMBER_BOOK_APPOINTMENT_REQUEST_INITIATED"
};
